-define(ERR_NO_SERVER_AVAILABLE, no_server_available).
-define(ERR_TIMEOUT, timeout).
-define(ERR_INVALID_JSON, invalid_json).
-define(ERR_SEND_TO_MCP_SERVER_FAILED, send_to_mcp_server_failed).
-define(ERR_INVALID_SERVER_RESPONSE, invalid_server_response).
-define(ERR_WRONG_RPC_ID, wrong_rpc_id).
-define(ERR_MALFORMED_JSON_RPC, malformed_json_rpc).
-define(ERR_UNEXPECTED_METHOD, unexpected_method).
-define(ERR_REQUIRED_FILED_MISSING, required_filed_missing).
-define(ERR_INVALID_CURSOR, invalid_cursor).
-define(ERR_NOT_INITIALIZED, not_initialized).
-define(ERR_NOT_IMPLEMENTED_METHOD, not_implemented_method).
-define(ERR_INTERNAL_ERROR, internal_error).
-define(ERR_NOT_FOUND, not_found).

-define(ERR_C_NO_SERVER_AVAILABLE, 1000).
-define(ERR_C_TIMEOUT, 1001).
-define(ERR_C_INVALID_JSON, 1002).
-define(ERR_C_SEND_TO_MCP_SERVER_FAILED, 1003).
-define(ERR_C_INVALID_SERVER_RESPONSE, 1004).
-define(ERR_C_WRONG_RPC_ID, 1005).
-define(ERR_C_MALFORMED_JSON_RPC, 1006).
-define(ERR_C_UNEXPECTED_METHOD, 1007).
-define(ERR_C_REQUIRED_FILED_MISSING, 1008).
-define(ERR_C_INVALID_CURSOR, 1009).
-define(ERR_C_NOT_INITIALIZED, 1010).
-define(ERR_C_NOT_IMPLEMENTED_METHOD, 1011).
-define(ERR_C_INTERNAL_ERROR, 1012).
-define(ERR_C_NOT_FOUND, 404).

-define(ERR_UNSUPPORTED_PROTOCOL_VERSION, unsupported_protocol_version).
-define(ERR_C_UNSUPPORTED_PROTOCOL_VERSION, -32602).

-define(ERR_CODE(ERR),
    case ERR of
        ?ERR_NO_SERVER_AVAILABLE -> ?ERR_C_NO_SERVER_AVAILABLE;
        ?ERR_TIMEOUT -> ?ERR_C_TIMEOUT;
        ?ERR_INVALID_JSON -> ?ERR_C_INVALID_JSON;
        ?ERR_SEND_TO_MCP_SERVER_FAILED -> ?ERR_C_SEND_TO_MCP_SERVER_FAILED;
        ?ERR_INVALID_SERVER_RESPONSE -> ?ERR_C_INVALID_SERVER_RESPONSE;
        ?ERR_WRONG_RPC_ID -> ?ERR_C_WRONG_RPC_ID;
        ?ERR_MALFORMED_JSON_RPC -> ?ERR_C_MALFORMED_JSON_RPC;
        ?ERR_UNEXPECTED_METHOD -> ?ERR_C_UNEXPECTED_METHOD;
        ?ERR_REQUIRED_FILED_MISSING -> ?ERR_C_REQUIRED_FILED_MISSING;
        ?ERR_INVALID_CURSOR -> ?ERR_C_INVALID_CURSOR;
        ?ERR_NOT_INITIALIZED -> ?ERR_C_NOT_INITIALIZED;
        ?ERR_NOT_IMPLEMENTED_METHOD -> ?ERR_C_NOT_IMPLEMENTED_METHOD;
        ?ERR_INTERNAL_ERROR -> ?ERR_C_INTERNAL_ERROR;
        ?ERR_NOT_FOUND -> ?ERR_C_NOT_FOUND;
        ?ERR_UNSUPPORTED_PROTOCOL_VERSION -> ?ERR_C_UNSUPPORTED_PROTOCOL_VERSION
    end
).
